// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: proto/metadata.proto

package metadata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	UploadedAt    string                 `protobuf:"bytes,5,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_proto_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_proto_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *FileMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileMetadata) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FileMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileMetadata) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileMetadata) GetUploadedAt() string {
	if x != nil {
		return x.UploadedAt
	}
	return ""
}

type SaveStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveStatus) Reset() {
	*x = SaveStatus{}
	mi := &file_proto_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveStatus) ProtoMessage() {}

func (x *SaveStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveStatus.ProtoReflect.Descriptor instead.
func (*SaveStatus) Descriptor() ([]byte, []int) {
	return file_proto_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *SaveStatus) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_proto_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_proto_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *FileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_proto_metadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_proto_metadata_proto_rawDescGZIP(), []int{3}
}

func (x *UserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FileList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileMetadata        `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileList) Reset() {
	*x = FileList{}
	mi := &file_proto_metadata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileList) ProtoMessage() {}

func (x *FileList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileList.ProtoReflect.Descriptor instead.
func (*FileList) Descriptor() ([]byte, []int) {
	return file_proto_metadata_proto_rawDescGZIP(), []int{4}
}

func (x *FileList) GetFiles() []*FileMetadata {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_proto_metadata_proto protoreflect.FileDescriptor

const file_proto_metadata_proto_rawDesc = "" +
	"\n" +
	"\x14proto/metadata.proto\x12\bmetadata\"\x88\x01\n" +
	"\fFileMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x1f\n" +
	"\vuploaded_at\x18\x05 \x01(\tR\n" +
	"uploadedAt\"@\n" +
	"\n" +
	"SaveStatus\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"B\n" +
	"\vFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"&\n" +
	"\vUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"8\n" +
	"\bFileList\x12,\n" +
	"\x05files\x18\x01 \x03(\v2\x16.metadata.FileMetadataR\x05files2\xc5\x01\n" +
	"\x0fMetadataService\x12<\n" +
	"\fSaveMetadata\x12\x16.metadata.FileMetadata\x1a\x14.metadata.SaveStatus\x12<\n" +
	"\vGetMetadata\x12\x15.metadata.FileRequest\x1a\x16.metadata.FileMetadata\x126\n" +
	"\tListFiles\x12\x15.metadata.UserRequest\x1a\x12.metadata.FileListB6Z4github.com/JawherKl/grpc-file-sharing/proto/metadatab\x06proto3"

var (
	file_proto_metadata_proto_rawDescOnce sync.Once
	file_proto_metadata_proto_rawDescData []byte
)

func file_proto_metadata_proto_rawDescGZIP() []byte {
	file_proto_metadata_proto_rawDescOnce.Do(func() {
		file_proto_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_metadata_proto_rawDesc), len(file_proto_metadata_proto_rawDesc)))
	})
	return file_proto_metadata_proto_rawDescData
}

var file_proto_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_metadata_proto_goTypes = []any{
	(*FileMetadata)(nil), // 0: metadata.FileMetadata
	(*SaveStatus)(nil),   // 1: metadata.SaveStatus
	(*FileRequest)(nil),  // 2: metadata.FileRequest
	(*UserRequest)(nil),  // 3: metadata.UserRequest
	(*FileList)(nil),     // 4: metadata.FileList
}
var file_proto_metadata_proto_depIdxs = []int32{
	0, // 0: metadata.FileList.files:type_name -> metadata.FileMetadata
	0, // 1: metadata.MetadataService.SaveMetadata:input_type -> metadata.FileMetadata
	2, // 2: metadata.MetadataService.GetMetadata:input_type -> metadata.FileRequest
	3, // 3: metadata.MetadataService.ListFiles:input_type -> metadata.UserRequest
	1, // 4: metadata.MetadataService.SaveMetadata:output_type -> metadata.SaveStatus
	0, // 5: metadata.MetadataService.GetMetadata:output_type -> metadata.FileMetadata
	4, // 6: metadata.MetadataService.ListFiles:output_type -> metadata.FileList
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_metadata_proto_init() }
func file_proto_metadata_proto_init() {
	if File_proto_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_metadata_proto_rawDesc), len(file_proto_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_metadata_proto_goTypes,
		DependencyIndexes: file_proto_metadata_proto_depIdxs,
		MessageInfos:      file_proto_metadata_proto_msgTypes,
	}.Build()
	File_proto_metadata_proto = out.File
	file_proto_metadata_proto_goTypes = nil
	file_proto_metadata_proto_depIdxs = nil
}
